version: "3.8"

services:

      # mongo:
      #   image: mongo
      #   restart: always
      #   environment:
      #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-user}
      #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-pass}
      #   volumes:
      #     - db_data:/data/db
      #   ports:
      #     - 127.0.0.1:27017:27017

      # mongo-express:
      #   image: mongo-express
      #   restart: always
      #   ports:
      #     - 127.0.0.1:8081:8081
      #   environment:
      #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-user}
      #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-pass}
      #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-user}:${MONGO_INITDB_ROOT_PASSWORD:-pass}@mongo:27017/
      #   depends_on:
      #     - mongo

      app:
            build: .
            restart: always
            command: bash ./start_server.sh
            environment:
                  # MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-user}:${MONGO_INITDB_ROOT_PASSWORD:-pass}@mongo/oculo
                  MONGO_HOST: ${MONGO_HOST}
                  MONGO_PORT: ${MONGO_PORT}
                  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
                  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ports:
                  - 127.0.0.1:${APP_LOCAL_PORT:-8070}:80

volumes:
      db_data:
